# Generated by Django 5.2.12 on 2026-03-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_listing_price_listing_max_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='distance_from_college',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='distance_from_metro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='food',
            field=models.CharField(choices=[('veg', 'Veg Only'), ('nonveg', 'Non-Veg'), ('both', 'Veg & Non-Veg'), ('none', 'No Food')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='minimum_stay',
            field=models.CharField(choices=[('1', '1 Month'), ('3', '3 Months'), ('6', '6 Months'), ('12', '12 Months')], default='1', max_length=5),
        ),
        migrations.AddField(
            model_name='listing',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='owner_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='listing',
            name='pg_type',
            field=models.CharField(choices=[('pg', 'PG'), ('hostel', 'Hostel'), ('coliving', 'Co-Living')], default='pg', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='listings/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('triple', 'Triple'), ('dormitory', 'Dormitory')], default='single', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='security_deposit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='amenities',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(default='Navi Mumbai', max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='gender',
            field=models.CharField(choices=[('any', 'Any'), ('ladies', 'Ladies Only'), ('gents', 'Gents Only')], default='any', max_length=20),
        ),
    ]
