# Generated by Django 5.2.12 on 2026-03-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_distance_from_college_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='security_deposit',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
