# Generated by Django 5.2.12 on 2026-03-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listing_security_deposit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='room_type',
        ),
        migrations.AddField(
            model_name='listing',
            name='has_dormitory',
            field=models.BooleanField(default=False, verbose_name='Dormitory'),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_double',
            field=models.BooleanField(default=False, verbose_name='Double Room'),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_single',
            field=models.BooleanField(default=False, verbose_name='Single Room'),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_triple',
            field=models.BooleanField(default=False, verbose_name='Triple Room'),
        ),
    ]
