# Generated by Django 5.2.12 on 2026-03-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_remove_listing_room_type_listing_has_dormitory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='listing',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Show on Website'),
        ),
    ]
