# Generated by Django 5.2.12 on 2026-03-14 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_remove_listing_is_verified_listing_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveListing',
            fields=[
            ],
            options={
                'verbose_name': '✅ Active Listing',
                'verbose_name_plural': '✅ Active Listings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('listings.listing',),
        ),
        migrations.CreateModel(
            name='InactiveListing',
            fields=[
            ],
            options={
                'verbose_name': '⏸️ Paused Listing',
                'verbose_name_plural': '⏸️ Paused Listings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('listings.listing',),
        ),
    ]
